import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "@/components/Providers";
import { GlobalBackground } from "@/components/GlobalBackground";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { prisma } from "@/lib/prisma";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  let userPrefs = { theme: 'system', backgroundMode: 'empty' };

  if (session?.user?.id) {
    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { theme: true, backgroundMode: true }
    });
    if (user) {
      userPrefs = { theme: user.theme || 'system', backgroundMode: user.backgroundMode || 'empty' };
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers initialTheme={userPrefs.theme} initialBgMode={userPrefs.backgroundMode}>
          <GlobalBackground />
          {children}
        </Providers>
      </body>
    </html>
  );
}
